---
- name: Switch NGINX Configuration for raigdkaragro.com
  hosts: localhost
  become: yes
  vars:
    current_color: "{{ deployment_color }}"  # Passed from Jenkins

  tasks:
    - name: Set NGINX configuration for blue-green deployment
      copy:
        content: |
          # NGINX configuration for raigdkaragro.com
          # Site: raigdkaragro.com (Agricultural Platform)
          # This configuration dynamically routes traffic to the active deployment (blue or green).
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              server_name raigdkaragro.com www.raigdkaragro.com;

              location / {
                  # Dynamically route to the active deployment container
                  proxy_pass http://localhost:{{ '8081' if current_color == 'blue' else '8082' }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
              }

              location ~ /\.(ht|HT) {
                  deny all;
              }
          }
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx

    - name: Test NGINX configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
